ARGUMENT_DATA_TYPE_UNKNOWN = 0
ARGUMENT_DATA_TYPE_BOOLEAN = 1
ARGUMENT_DATA_TYPE_INTEGER = 2
ARGUMENT_DATA_TYPE_FLOAT = 3
ARGUMENT_DATA_TYPE_COMPLEX = 4
ARGUMENT_DATA_TYPE_STRING = 5
EVENT_SHORT_DESC_MAX_LENGTH = 32

EVENT_FIELDS_MAP = ("event","category","email")

EVENT_MODEL_NAMES = {
	"click": "ClickEvent"
}

EVENT_TYPES_EXTRA_FIELDS_MAP = {
	"UNKNOWN": None,
	"DEFERRED": ("response", "attempt"),
	"PROCESSED": (),
	"DROPPED": ("reason"),
	"DELIVERED": ("response"),
	"BOUNCE": ("status", "reason", "type"),
	"OPEN": (),
	"CLICK": ("url", ),
	"UNSUBSCRIBE": (),
	"SPAMREPORT": (),
}
